label: Castellano
pages:
    -
        label: The Black Hack
        author: Rafael Pardo Macías
        version: '0.5'
    -
        label: Additional Things
        author: Rafael Pardo Macías
        version: '0.1'
        filename: additional-things.md

